/**
 * Catálogo de veículos compatível com o padrão Mercado Livre.
 *
 * Estrutura hierárquica: Marca → Modelo → Anos → Versões
 *
 * As marcas, modelos, anos e versões seguem o padrão oficial do ML para
 * compatibilidade de autopeças no mercado brasileiro.
 */

export interface VehicleVersion {
  name: string;
}

export interface VehicleModel {
  name: string;
  yearFrom: number;
  yearTo: number;
  versions: string[];
}

export interface VehicleBrand {
  name: string;
  models: VehicleModel[];
}

// ---------------------------------------------------------------------------
// Catálogo completo
// ---------------------------------------------------------------------------

export const VEHICLE_CATALOG: VehicleBrand[] = [
  // ── ALFA ROMEO ──────────────────────────────────────────────────────────
  {
    name: "Alfa Romeo",
    models: [
      {
        name: "145",
        yearFrom: 1995,
        yearTo: 1999,
        versions: ["Quadrifoglio", "TS", "TD"],
      },
      {
        name: "147",
        yearFrom: 2001,
        yearTo: 2010,
        versions: ["TS", "2.0", "GTA"],
      },
      {
        name: "156",
        yearFrom: 1998,
        yearTo: 2006,
        versions: ["2.0 TS", "2.5 V6", "JTD", "GTA"],
      },
      {
        name: "159",
        yearFrom: 2005,
        yearTo: 2011,
        versions: ["2.2 JTS", "3.2 V6", "JTD"],
      },
      {
        name: "166",
        yearFrom: 1998,
        yearTo: 2007,
        versions: ["2.0 TS", "3.0 V6", "2.4 JTD"],
      },
      {
        name: "Giulietta",
        yearFrom: 2010,
        yearTo: 2020,
        versions: ["1.4 TB", "1.8 TBi", "2.0 JTDM"],
      },
      {
        name: "Mito",
        yearFrom: 2008,
        yearTo: 2018,
        versions: ["1.4", "1.4 TB", "Quadrifoglio Verde"],
      },
      {
        name: "Spider",
        yearFrom: 1995,
        yearTo: 2006,
        versions: ["2.0 TS", "3.0 V6", "2.0 JTS"],
      },
      {
        name: "Stelvio",
        yearFrom: 2017,
        yearTo: 2025,
        versions: ["2.0 Turbo", "2.2 Diesel", "Quadrifoglio"],
      },
      {
        name: "Giulia",
        yearFrom: 2016,
        yearTo: 2025,
        versions: ["2.0 Turbo", "2.2 Diesel", "Quadrifoglio"],
      },
    ],
  },

  // ── AUDI ────────────────────────────────────────────────────────────────
  {
    name: "Audi",
    models: [
      {
        name: "A1",
        yearFrom: 2010,
        yearTo: 2025,
        versions: ["1.4 TFSI", "1.0 TFSI", "Sportback", "S Line"],
      },
      {
        name: "A3",
        yearFrom: 1997,
        yearTo: 2025,
        versions: [
          "1.4 TFSI",
          "1.8 TFSI",
          "2.0 TFSI",
          "Sedan",
          "Sportback",
          "S Line",
          "Ambition",
        ],
      },
      {
        name: "A4",
        yearFrom: 1995,
        yearTo: 2025,
        versions: [
          "1.8 TFSI",
          "2.0 TFSI",
          "Avant",
          "S Line",
          "Ambition",
          "Launch Edition",
        ],
      },
      {
        name: "A5",
        yearFrom: 2007,
        yearTo: 2025,
        versions: ["2.0 TFSI", "Sportback", "Coupé", "Cabriolet", "S Line"],
      },
      {
        name: "A6",
        yearFrom: 1995,
        yearTo: 2025,
        versions: ["2.0 TFSI", "3.0 TFSI", "Avant", "S Line"],
      },
      {
        name: "A7",
        yearFrom: 2011,
        yearTo: 2025,
        versions: ["3.0 TFSI", "Sportback", "S Line"],
      },
      {
        name: "A8",
        yearFrom: 2002,
        yearTo: 2025,
        versions: ["3.0 TFSI", "4.0 TFSI", "L"],
      },
      {
        name: "Q3",
        yearFrom: 2012,
        yearTo: 2025,
        versions: [
          "1.4 TFSI",
          "2.0 TFSI",
          "Sportback",
          "S Line",
          "Black Edition",
        ],
      },
      {
        name: "Q5",
        yearFrom: 2009,
        yearTo: 2025,
        versions: ["2.0 TFSI", "Sportback", "S Line", "Ambition"],
      },
      {
        name: "Q7",
        yearFrom: 2006,
        yearTo: 2025,
        versions: ["3.0 TFSI", "3.0 TDI", "S Line"],
      },
      {
        name: "Q8",
        yearFrom: 2019,
        yearTo: 2025,
        versions: ["3.0 TFSI", "S Line"],
      },
      {
        name: "TT",
        yearFrom: 1999,
        yearTo: 2023,
        versions: ["2.0 TFSI", "Coupé", "Roadster", "S Line"],
      },
      {
        name: "RS3",
        yearFrom: 2015,
        yearTo: 2025,
        versions: ["2.5 TFSI", "Sedan", "Sportback"],
      },
      {
        name: "RS4",
        yearFrom: 2006,
        yearTo: 2025,
        versions: ["2.9 TFSI", "Avant"],
      },
      {
        name: "RS5",
        yearFrom: 2010,
        yearTo: 2025,
        versions: ["2.9 TFSI", "Coupé", "Sportback"],
      },
      {
        name: "RS6",
        yearFrom: 2008,
        yearTo: 2025,
        versions: ["4.0 TFSI", "Avant"],
      },
      {
        name: "RS7",
        yearFrom: 2013,
        yearTo: 2025,
        versions: ["4.0 TFSI", "Sportback"],
      },
      { name: "RSQ8", yearFrom: 2020, yearTo: 2025, versions: ["4.0 TFSI"] },
      {
        name: "S3",
        yearFrom: 2007,
        yearTo: 2025,
        versions: ["2.0 TFSI", "Sedan", "Sportback"],
      },
      {
        name: "e-tron",
        yearFrom: 2019,
        yearTo: 2025,
        versions: ["55 quattro", "Sportback", "GT", "S"],
      },
      {
        name: "e-tron GT",
        yearFrom: 2021,
        yearTo: 2025,
        versions: ["quattro", "RS"],
      },
    ],
  },

  // ── BMW ─────────────────────────────────────────────────────────────────
  {
    name: "BMW",
    models: [
      {
        name: "Série 1",
        yearFrom: 2004,
        yearTo: 2025,
        versions: ["118i", "120i", "125i", "M135i", "M Sport"],
      },
      {
        name: "Série 2",
        yearFrom: 2014,
        yearTo: 2025,
        versions: [
          "218i",
          "220i",
          "M235i",
          "M240i",
          "Gran Coupé",
          "Active Tourer",
        ],
      },
      {
        name: "Série 3",
        yearFrom: 1990,
        yearTo: 2025,
        versions: [
          "318i",
          "320i",
          "325i",
          "328i",
          "330i",
          "335i",
          "340i",
          "M Sport",
          "Touring",
        ],
      },
      {
        name: "Série 4",
        yearFrom: 2013,
        yearTo: 2025,
        versions: ["420i", "430i", "M440i", "Gran Coupé", "M Sport"],
      },
      {
        name: "Série 5",
        yearFrom: 1996,
        yearTo: 2025,
        versions: [
          "520i",
          "525i",
          "528i",
          "530i",
          "535i",
          "540i",
          "M Sport",
          "Touring",
        ],
      },
      {
        name: "Série 6",
        yearFrom: 2003,
        yearTo: 2018,
        versions: ["640i", "650i", "Gran Coupé"],
      },
      {
        name: "Série 7",
        yearFrom: 2002,
        yearTo: 2025,
        versions: ["740i", "745i", "750i", "M Sport"],
      },
      {
        name: "Série 8",
        yearFrom: 2018,
        yearTo: 2025,
        versions: ["840i", "M850i", "Gran Coupé", "M Sport"],
      },
      {
        name: "X1",
        yearFrom: 2010,
        yearTo: 2025,
        versions: ["sDrive18i", "sDrive20i", "xDrive25i", "M Sport"],
      },
      {
        name: "X2",
        yearFrom: 2018,
        yearTo: 2025,
        versions: ["sDrive18i", "sDrive20i", "M35i", "M Sport"],
      },
      {
        name: "X3",
        yearFrom: 2004,
        yearTo: 2025,
        versions: [
          "xDrive20i",
          "xDrive30i",
          "M40i",
          "M Sport",
          "M Competition",
        ],
      },
      {
        name: "X4",
        yearFrom: 2014,
        yearTo: 2025,
        versions: ["xDrive20i", "xDrive30i", "M40i", "M Sport"],
      },
      {
        name: "X5",
        yearFrom: 2000,
        yearTo: 2025,
        versions: ["xDrive30i", "xDrive40i", "xDrive50i", "M50i", "M Sport"],
      },
      {
        name: "X6",
        yearFrom: 2008,
        yearTo: 2025,
        versions: ["xDrive30i", "xDrive40i", "M50i", "M Sport"],
      },
      {
        name: "X7",
        yearFrom: 2019,
        yearTo: 2025,
        versions: ["xDrive40i", "xDrive50i", "M50i", "M Sport"],
      },
      {
        name: "Z4",
        yearFrom: 2003,
        yearTo: 2025,
        versions: ["sDrive20i", "sDrive30i", "M40i"],
      },
      {
        name: "M2",
        yearFrom: 2016,
        yearTo: 2025,
        versions: ["Competition", "CS"],
      },
      {
        name: "M3",
        yearFrom: 1992,
        yearTo: 2025,
        versions: ["Competition", "CS", "Touring"],
      },
      {
        name: "M4",
        yearFrom: 2014,
        yearTo: 2025,
        versions: ["Competition", "CS", "CSL", "Cabriolet"],
      },
      {
        name: "M5",
        yearFrom: 2005,
        yearTo: 2025,
        versions: ["Competition", "CS"],
      },
      {
        name: "iX",
        yearFrom: 2021,
        yearTo: 2025,
        versions: ["xDrive40", "xDrive50", "M60"],
      },
      { name: "iX3", yearFrom: 2021, yearTo: 2025, versions: ["M Sport"] },
      {
        name: "i4",
        yearFrom: 2022,
        yearTo: 2025,
        versions: ["eDrive35", "eDrive40", "M50"],
      },
    ],
  },

  // ── BYD ─────────────────────────────────────────────────────────────────
  {
    name: "BYD",
    models: [
      {
        name: "Dolphin",
        yearFrom: 2023,
        yearTo: 2025,
        versions: ["GS", "GL", "Plus"],
      },
      { name: "Dolphin Mini", yearFrom: 2024, yearTo: 2025, versions: ["Elétrico"] },
      {
        name: "Seal",
        yearFrom: 2023,
        yearTo: 2025,
        versions: ["Design", "Excellence"],
      },
      {
        name: "Song Plus",
        yearFrom: 2023,
        yearTo: 2025,
        versions: ["GL", "GS", "Premium"],
      },
      {
        name: "Song Pro",
        yearFrom: 2024,
        yearTo: 2025,
        versions: ["GL", "GS"],
      },
      {
        name: "Yuan Plus",
        yearFrom: 2023,
        yearTo: 2025,
        versions: ["GL", "GS"],
      },
      { name: "Tan", yearFrom: 2023, yearTo: 2025, versions: ["EV"] },
      { name: "Han", yearFrom: 2024, yearTo: 2025, versions: ["EV"] },
      { name: "King", yearFrom: 2024, yearTo: 2025, versions: ["GL", "GS"] },
    ],
  },

  // ── CAOA CHERY ──────────────────────────────────────────────────────────
  {
    name: "CAOA Chery",
    models: [
      {
        name: "Tiggo 2",
        yearFrom: 2018,
        yearTo: 2025,
        versions: ["Look", "Act", "1.5"],
      },
      {
        name: "Tiggo 3X",
        yearFrom: 2020,
        yearTo: 2025,
        versions: ["Look", "Act", "Turbo", "1.0", "1.5 Turbo"],
      },
      { name: "Tiggo 4", yearFrom: 2022, yearTo: 2025, versions: ["1.5 Turbo"] },
      {
        name: "Tiggo 5X",
        yearFrom: 2018,
        yearTo: 2025,
        versions: ["T", "TXS", "Pro", "1.5 Turbo"],
      },
      {
        name: "Tiggo 7",
        yearFrom: 2019,
        yearTo: 2025,
        versions: ["T", "TXS", "Pro", "1.5 Turbo"],
      },
      { name: "Tiggo 7 Pro", yearFrom: 2022, yearTo: 2025, versions: ["1.5 Turbo"] },
      {
        name: "Tiggo 8",
        yearFrom: 2020,
        yearTo: 2025,
        versions: ["T", "TXS", "Pro", "1.5 Turbo", "1.6 Turbo"],
      },
      {
        name: "Arrizo 5",
        yearFrom: 2020,
        yearTo: 2023,
        versions: ["1.5 Turbo"],
      },
      {
        name: "Arrizo 6",
        yearFrom: 2020,
        yearTo: 2025,
        versions: ["1.5 Turbo", "Pro", "GS", "GSX"],
      },
      { name: "iCar", yearFrom: 2024, yearTo: 2025, versions: ["Elétrico"] },
    ],
  },

  // ── CHEVROLET ───────────────────────────────────────────────────────────
  {
    name: "Chevrolet",
    models: [
      { name: "Agile", yearFrom: 2009, yearTo: 2014, versions: ["LT", "LTZ", "1.4"] },
      {
        name: "Astra",
        yearFrom: 1999,
        yearTo: 2011,
        versions: [
          "GL",
          "GLS",
          "CD",
          "Advantage",
          "Elegance",
          "Sedan",
          "Hatch",
          "1.8",
          "2.0",
        ],
      },
      {
        name: "Blazer",
        yearFrom: 1996,
        yearTo: 2011,
        versions: ["DLX", "Advantage", "Executive", "4.3 V6", "2.2", "2.4", "2.8 Turbo Diesel"],
      },
      {
        name: "Bolt EV",
        yearFrom: 2021,
        yearTo: 2025,
        versions: ["Premier", "LT"],
      },
      {
        name: "Bolt EUV",
        yearFrom: 2022,
        yearTo: 2025,
        versions: ["Premier", "LT"],
      },
      {
        name: "Camaro",
        yearFrom: 2010,
        yearTo: 2024,
        versions: ["SS", "LT", "RS", "ZL1", "1LE", "Conversível", "2.0 Turbo", "6.2 V8"],
      },
      {
        name: "Captiva",
        yearFrom: 2008,
        yearTo: 2025,
        versions: ["Sport", "Ecotec", "2.4", "1.5 Turbo", "Premier"],
      },
      {
        name: "Celta",
        yearFrom: 2000,
        yearTo: 2015,
        versions: ["Life", "Spirit", "LT", "LS", "1.0"],
      },
      {
        name: "Classic",
        yearFrom: 2003,
        yearTo: 2016,
        versions: ["LS", "Advantage", "Spirit", "VHC", "1.0"],
      },
      {
        name: "Cobalt",
        yearFrom: 2012,
        yearTo: 2020,
        versions: ["LT", "LTZ", "Elite", "Advantage", "1.4", "1.8"],
      },
      {
        name: "Corsa",
        yearFrom: 1994,
        yearTo: 2012,
        versions: [
          "Wind",
          "Super",
          "GL",
          "GLS",
          "Classic",
          "Sedan",
          "Hatch",
          "Premium",
          "Maxx",
          "Joy",
          "1.0",
          "1.4",
          "1.6",
          "1.8",
        ],
      },
      {
        name: "Cruze",
        yearFrom: 2012,
        yearTo: 2025,
        versions: [
          "LT",
          "LTZ",
          "Premier",
          "Sport6",
          "Sedan",
          "Hatch",
          "Midnight",
          "Black Bow Tie",
          "1.4 Turbo",
          "1.8",
        ],
      },
      {
        name: "Equinox",
        yearFrom: 2018,
        yearTo: 2025,
        versions: ["LT", "Premier", "RS", "Midnight", "1.5 Turbo", "2.0 Turbo"],
      },
      {
        name: "Joy",
        yearFrom: 2017,
        yearTo: 2021,
        versions: ["1.0", "1.0 Plus", "Black"],
      },
      {
        name: "Malibu",
        yearFrom: 2010,
        yearTo: 2019,
        versions: ["LTZ", "2.4"],
      },
      {
        name: "Meriva",
        yearFrom: 2003,
        yearTo: 2012,
        versions: ["Joy", "Maxx", "Premium", "SS", "1.4", "1.8"],
      },
      {
        name: "Montana",
        yearFrom: 2004,
        yearTo: 2025,
        versions: ["LS", "LT", "LTZ", "Conquest", "Sport", "Turbo", "Premier", "1.4", "1.8", "1.2 Turbo"],
      },
      {
        name: "Monza",
        yearFrom: 1982,
        yearTo: 1996,
        versions: ["SL", "SL/E", "Classic", "GLS", "1.8", "2.0"],
      },
      {
        name: "Onix",
        yearFrom: 2013,
        yearTo: 2025,
        versions: [
          "LT",
          "LTZ",
          "Premier",
          "Joy",
          "Activ",
          "Plus",
          "RS",
          "Midnight",
          "1.0",
          "1.0 Turbo",
          "1.4",
        ],
      },
      {
        name: "Onix Plus",
        yearFrom: 2020,
        yearTo: 2025,
        versions: ["LT", "LTZ", "Premier", "Midnight", "1.0", "1.0 Turbo"],
      },
      {
        name: "Prisma",
        yearFrom: 2007,
        yearTo: 2020,
        versions: ["LT", "LTZ", "Joy", "Advantage", "Maxx", "1.0", "1.4"],
      },
      {
        name: "S10",
        yearFrom: 1995,
        yearTo: 2025,
        versions: [
          "LS",
          "LT",
          "LTZ",
          "High Country",
          "Advantage",
          "Executive",
          "Rodeio",
          "Cabine Simples",
          "Cabine Dupla",
          "2.4 Flex",
          "2.5 Flex",
          "2.8 Diesel",
        ],
      },
      {
        name: "Silverado",
        yearFrom: 1997,
        yearTo: 2002,
        versions: ["DLX", "D20", "Grand Blazer", "4.1", "4.2 Diesel"],
      },
      {
        name: "Spin",
        yearFrom: 2013,
        yearTo: 2025,
        versions: ["LT", "LTZ", "Activ", "Premier", "Advantage", "1.0 Turbo", "1.8"],
      },
      {
        name: "Tracker",
        yearFrom: 2014,
        yearTo: 2025,
        versions: ["LT", "LTZ", "Premier", "Midnight", "RS", "1.0 Turbo", "1.2 Turbo", "1.4 Turbo", "1.8"],
      },
      {
        name: "TrailBlazer",
        yearFrom: 2013,
        yearTo: 2025,
        versions: ["LT", "LTZ", "Premier", "2.8 Diesel", "3.6 V6"],
      },
      {
        name: "Trax",
        yearFrom: 2024,
        yearTo: 2025,
        versions: ["LT", "Premier", "RS", "Activ", "1.0 Turbo"],
      },
      {
        name: "Vectra",
        yearFrom: 1993,
        yearTo: 2011,
        versions: [
          "GL",
          "GLS",
          "CD",
          "Expression",
          "Elegance",
          "Elite",
          "GT",
          "GTX",
          "2.0",
          "2.2",
          "2.4",
        ],
      },
      {
        name: "Zafira",
        yearFrom: 2001,
        yearTo: 2012,
        versions: ["CD", "Elegance", "Expression", "Elite", "Comfort", "2.0"],
      },
    ],
  },

  // ── CITROËN ─────────────────────────────────────────────────────────────
  {
    name: "Citroën",
    models: [
      {
        name: "Aircross",
        yearFrom: 2011,
        yearTo: 2019,
        versions: ["Start", "Feel", "Shine", "Live", "Tendance", "1.5", "1.6"],
      },
      {
        name: "Berlingo",
        yearFrom: 1999,
        yearTo: 2019,
        versions: ["1.6", "GLX", "Multispace"],
      },
      {
        name: "C3",
        yearFrom: 2003,
        yearTo: 2025,
        versions: [
          "GLX",
          "Exclusive",
          "Tendance",
          "Origine",
          "Attraction",
          "Feel",
          "Shine",
          "Live",
          "First Edition",
          "You",
          "1.4",
          "1.5",
          "1.6",
        ],
      },
      {
        name: "C3 Aircross",
        yearFrom: 2019,
        yearTo: 2025,
        versions: ["Feel", "Shine", "Live", "First Edition", "1.6"],
      },
      {
        name: "C4 Cactus",
        yearFrom: 2018,
        yearTo: 2023,
        versions: ["Feel", "Shine", "Live", "1.6", "1.6 THP"],
      },
      {
        name: "C4 Lounge",
        yearFrom: 2014,
        yearTo: 2019,
        versions: ["Tendance", "Exclusive", "THP", "Feel", "1.6 THP", "2.0"],
      },
      {
        name: "C4 Pallas",
        yearFrom: 2007,
        yearTo: 2013,
        versions: ["GLX", "Exclusive", "2.0"],
      },
      {
        name: "C5",
        yearFrom: 2002,
        yearTo: 2017,
        versions: ["Exclusive", "2.0"],
      },
      {
        name: "DS3",
        yearFrom: 2012,
        yearTo: 2019,
        versions: ["Sport Chic", "So Chic", "1.6 THP"],
      },
      {
        name: "DS4",
        yearFrom: 2013,
        yearTo: 2018,
        versions: ["So Chic", "1.6 THP"],
      },
      {
        name: "DS5",
        yearFrom: 2013,
        yearTo: 2016,
        versions: ["So Chic", "1.6 THP"],
      },
      {
        name: "Grand C4 Picasso",
        yearFrom: 2007,
        yearTo: 2018,
        versions: ["Exclusive", "Intensive", "GLX", "2.0"],
      },
      {
        name: "Jumpy",
        yearFrom: 2018,
        yearTo: 2025,
        versions: ["Vitré", "Pack", "Furgão", "1.5 Turbo Diesel", "1.6 Turbo Diesel"],
      },
      {
        name: "Xsara Picasso",
        yearFrom: 2001,
        yearTo: 2012,
        versions: ["GLX", "Exclusive", "2.0"],
      },
      {
        name: "ë-C3",
        yearFrom: 2024,
        yearTo: 2025,
        versions: ["Feel", "Shine", "You"],
      },
    ],
  },

  // ── DODGE ───────────────────────────────────────────────────────────────
  {
    name: "Dodge",
    models: [
      {
        name: "Challenger",
        yearFrom: 2008,
        yearTo: 2023,
        versions: ["SXT", "R/T", "Scat Pack", "SRT Hellcat", "3.6 V6", "5.7 V8", "6.2 V8", "6.4 V8"],
      },
      {
        name: "Charger",
        yearFrom: 2006,
        yearTo: 2023,
        versions: ["SXT", "R/T", "Scat Pack", "SRT Hellcat", "3.6 V6", "5.7 V8", "6.2 V8", "6.4 V8"],
      },
      {
        name: "Durango",
        yearFrom: 2004,
        yearTo: 2025,
        versions: ["SXT", "GT", "R/T", "SRT", "3.6 V6", "5.7 V8", "6.4 V8"],
      },
      {
        name: "Journey",
        yearFrom: 2009,
        yearTo: 2020,
        versions: ["SE", "SXT", "R/T", "Crossroad", "2.7 V6", "3.6 V6"],
      },
      {
        name: "Ram 1500",
        yearFrom: 2012,
        yearTo: 2025,
        versions: ["Laramie", "Limited", "Rebel", "R/T", "Classic", "3.6 V6", "5.7 V8"],
      },
      {
        name: "Ram 2500",
        yearFrom: 2012,
        yearTo: 2025,
        versions: ["Laramie", "Limited", "6.7 Cummins"],
      },
      {
        name: "Ram 3500",
        yearFrom: 2019,
        yearTo: 2025,
        versions: ["Laramie", "Limited", "6.7 Cummins"],
      },
    ],
  },

  // ── FIAT ────────────────────────────────────────────────────────────────
  {
    name: "Fiat",
    models: [
      {
        name: "500",
        yearFrom: 2010,
        yearTo: 2025,
        versions: ["Cult", "Sport", "Lounge", "Cabrio", "Abarth", "1.4"],
      },
      {
        name: "Argo",
        yearFrom: 2017,
        yearTo: 2025,
        versions: ["Drive", "Trekking", "HGT", "1.0", "1.3", "1.8"],
      },
      {
        name: "Bravo",
        yearFrom: 2011,
        yearTo: 2016,
        versions: ["Absolute", "Essence", "Sporting", "T-Jet", "1.4 T-Jet", "1.8"],
      },
      {
        name: "Cronos",
        yearFrom: 2018,
        yearTo: 2025,
        versions: ["Drive", "Precision", "HGT", "1.0", "1.3", "1.8"],
      },
      {
        name: "Doblo",
        yearFrom: 2002,
        yearTo: 2025,
        versions: ["ELX", "HLX", "Attractive", "Essence", "Adventure", "Cargo", "1.3", "1.4", "1.6", "1.8"],
      },
      {
        name: "Ducato",
        yearFrom: 2006,
        yearTo: 2025,
        versions: ["Cargo", "Maxicargo", "Multijet", "Minibus", "Furgão", "2.3"],
      },
      {
        name: "Fastback",
        yearFrom: 2023,
        yearTo: 2025,
        versions: [
          "Audace",
          "Impetus",
          "Limited Edition",
          "Turbo 200",
          "Abarth",
          "1.0 Turbo",
          "1.3 Turbo",
        ],
      },
      {
        name: "Fiorino",
        yearFrom: 2004,
        yearTo: 2025,
        versions: ["Furgão", "Working", "Hard Working", "Endurance", "1.4"],
      },
      {
        name: "Freemont",
        yearFrom: 2012,
        yearTo: 2016,
        versions: ["Emotion", "Precision", "2.4", "2.0 Diesel"],
      },
      {
        name: "Grand Siena",
        yearFrom: 2012,
        yearTo: 2021,
        versions: ["Attractive", "Essence", "Tetrafuel", "EL", "1.4", "1.6"],
      },
      {
        name: "Idea",
        yearFrom: 2005,
        yearTo: 2016,
        versions: [
          "ELX",
          "HLX",
          "Attractive",
          "Essence",
          "Adventure",
          "Sporting",
          "1.4",
          "1.6",
          "1.8",
        ],
      },
      {
        name: "Linea",
        yearFrom: 2008,
        yearTo: 2016,
        versions: ["LX", "HLX", "Absolute", "Essence", "T-Jet", "1.8", "1.9"],
      },
      {
        name: "Marea",
        yearFrom: 1998,
        yearTo: 2007,
        versions: ["ELX", "HLX", "SX", "Turbo", "Weekend", "1.6", "1.8", "2.0", "2.4"],
      },
      {
        name: "Mobi",
        yearFrom: 2016,
        yearTo: 2025,
        versions: ["Easy", "Like", "Drive", "Way", "Trekking", "1.0"],
      },
      {
        name: "Palio",
        yearFrom: 1996,
        yearTo: 2017,
        versions: [
          "EDX",
          "EX",
          "ELX",
          "HLX",
          "Fire",
          "Economy",
          "Attractive",
          "Essence",
          "Sporting",
          "Weekend",
          "Adventure",
          "1.0",
          "1.3",
          "1.4",
          "1.6",
          "1.8",
        ],
      },
      {
        name: "Pulse",
        yearFrom: 2021,
        yearTo: 2025,
        versions: ["Drive", "Audace", "Impetus", "Turbo 200", "Abarth", "1.0 Turbo", "1.3 Turbo"],
      },
      {
        name: "Punto",
        yearFrom: 2007,
        yearTo: 2017,
        versions: [
          "ELX",
          "HLX",
          "Attractive",
          "Essence",
          "Sporting",
          "T-Jet",
          "Blackmotion",
          "1.4",
          "1.6",
          "1.8",
        ],
      },
      {
        name: "Scudo",
        yearFrom: 2022,
        yearTo: 2025,
        versions: ["Cargo", "Furgão", "1.5 Turbo Diesel"],
      },
      {
        name: "Siena",
        yearFrom: 1997,
        yearTo: 2012,
        versions: ["EX", "ELX", "HLX", "Fire", "EL", "Tetrafuel", "1.0", "1.3", "1.4", "1.6", "1.8"],
      },
      {
        name: "Stilo",
        yearFrom: 2002,
        yearTo: 2011,
        versions: [
          "1.8 8V",
          "1.8 8V Flex",
          "1.8 16V",
          "2.4 20V",
          "Attractive",
          "Connect",
          "Sporting",
          "Blackmotion",
          "Dualogic",
          "Abarth",
        ],
      },
      {
        name: "Strada",
        yearFrom: 1999,
        yearTo: 2025,
        versions: [
          "Working",
          "Hard Working",
          "Trekking",
          "Adventure",
          "Freedom",
          "Endurance",
          "Volcano",
          "Ranch",
          "Ultra",
          "Cabine Simples",
          "Cabine Dupla",
          "Cabine Plus",
          "1.3",
          "1.4",
          "1.3 Turbo",
          "1.8",
        ],
      },
      {
        name: "Toro",
        yearFrom: 2016,
        yearTo: 2025,
        versions: [
          "Freedom",
          "Volcano",
          "Ranch",
          "Ultra",
          "Endurance",
          "Turbo Diesel",
          "1.3 Turbo",
          "1.8",
          "2.0 Diesel",
          "2.4",
        ],
      },
      {
        name: "Toro (Diesel)",
        yearFrom: 2016,
        yearTo: 2025,
        versions: [
          "Freedom Diesel",
          "Volcano Diesel",
          "Ranch Diesel",
          "Ultra Diesel",
          "2.0 Diesel",
        ],
      },
      {
        name: "Uno",
        yearFrom: 1984,
        yearTo: 2021,
        versions: [
          "Mille",
          "CS",
          "S",
          "SX",
          "Smart",
          "Fire",
          "Economy",
          "Way",
          "Vivace",
          "Sporting",
          "Attractive",
          "Drive",
          "1.0",
          "1.4",
        ],
      },
      {
        name: "Titano",
        yearFrom: 2024,
        yearTo: 2025,
        versions: ["Freedom", "Volcano", "Ranch", "2.2 Diesel"],
      },
    ],
  },

  // ── FORD ────────────────────────────────────────────────────────────────
  {
    name: "Ford",
    models: [
      {
        name: "Bronco Sport",
        yearFrom: 2021,
        yearTo: 2025,
        versions: ["Wildtrak", "Badlands", "1.5 EcoBoost", "2.0 EcoBoost"],
      },
      {
        name: "Courier",
        yearFrom: 1997,
        yearTo: 2013,
        versions: ["L", "XL", "CLX", "1.0", "1.6"],
      },
      {
        name: "EcoSport",
        yearFrom: 2003,
        yearTo: 2022,
        versions: [
          "XL",
          "XLS",
          "XLT",
          "Freestyle",
          "Titanium",
          "Storm",
          "SE",
          "1.0 EcoBoost",
          "1.5",
          "1.6",
          "2.0",
        ],
      },
      {
        name: "Edge",
        yearFrom: 2012,
        yearTo: 2024,
        versions: ["SE", "SEL", "Limited", "Titanium", "ST", "2.0 EcoBoost", "3.5 V6"],
      },
      {
        name: "Escort",
        yearFrom: 1983,
        yearTo: 2003,
        versions: ["GL", "GLX", "XR3", "Ghia", "Hobby", "Zetec", "1.0", "1.6", "1.8", "2.0"],
      },
      {
        name: "F-250",
        yearFrom: 1999,
        yearTo: 2011,
        versions: ["XL", "XLT", "Tropical", "3.9 Diesel", "4.2"],
      },
      {
        name: "Fiesta",
        yearFrom: 1996,
        yearTo: 2019,
        versions: [
          "GL",
          "CLX",
          "Street",
          "Supercharger",
          "Rocam",
          "1.0",
          "1.4",
          "1.6",
          "SE",
          "SEL",
          "Titanium",
          "Hatch",
          "Sedan",
        ],
      },
      {
        name: "Focus",
        yearFrom: 2001,
        yearTo: 2019,
        versions: [
          "GL",
          "GLX",
          "Ghia",
          "Titanium",
          "SE",
          "SEL",
          "Hatch",
          "Sedan",
          "Fastback",
          "1.6",
          "2.0",
        ],
      },
      {
        name: "Fusion",
        yearFrom: 2006,
        yearTo: 2019,
        versions: ["SEL", "Titanium", "Hybrid", "2.5", "2.0 EcoBoost", "AWD"],
      },
      {
        name: "Ka",
        yearFrom: 1997,
        yearTo: 2021,
        versions: [
          "GL",
          "CLX",
          "Street",
          "Action",
          "Fly",
          "S",
          "SE",
          "SEL",
          "Titanium",
          "Freestyle",
          "SE Plus",
          "Hatch",
          "Sedan",
          "1.0",
          "1.5",
        ],
      },
      {
        name: "Maverick",
        yearFrom: 2022,
        yearTo: 2025,
        versions: ["Lariat", "XL", "XLT", "Hybrid", "EcoBoost", "FX4"],
      },
      {
        name: "Mustang",
        yearFrom: 2004,
        yearTo: 2025,
        versions: [
          "V6",
          "GT",
          "Premium",
          "EcoBoost",
          "Shelby GT350",
          "Shelby GT500",
          "Mach 1",
          "Dark Horse",
        ],
      },
      {
        name: "Mustang Mach-E",
        yearFrom: 2022,
        yearTo: 2025,
        versions: ["Select", "Premium", "GT"],
      },
      {
        name: "Ranger",
        yearFrom: 1994,
        yearTo: 2025,
        versions: [
          "XL",
          "XLS",
          "XLT",
          "Limited",
          "Wildtrak",
          "Raptor",
          "Storm",
          "Black",
          "Cabine Simples",
          "Cabine Dupla",
          "2.2 Diesel",
          "2.3 EcoBoost",
          "2.5",
          "3.0 V6 Diesel",
          "3.2 Diesel",
        ],
      },
      {
        name: "Territory",
        yearFrom: 2021,
        yearTo: 2025,
        versions: ["SEL", "Titanium", "1.5 EcoBoost"],
      },
      {
        name: "Transit",
        yearFrom: 2018,
        yearTo: 2025,
        versions: ["Furgão", "Chassis", "Minibus", "2.0 Diesel"],
      },
    ],
  },

  // ── GWM ─────────────────────────────────────────────────────────────────
  {
    name: "GWM",
    models: [
      {
        name: "Haval H6",
        yearFrom: 2022,
        yearTo: 2025,
        versions: ["GT", "HEV", "PHEV", "Supreme"],
      },
      { name: "Haval H6 GT", yearFrom: 2023, yearTo: 2025, versions: ["HEV", "PHEV"] },
      { name: "Haval Jolion", yearFrom: 2022, yearTo: 2025, versions: ["1.5 Turbo"] },
      {
        name: "ORA 03",
        yearFrom: 2023,
        yearTo: 2025,
        versions: ["Skin", "GT"],
      },
    ],
  },

  // ── HONDA ───────────────────────────────────────────────────────────────
  {
    name: "Honda",
    models: [
      {
        name: "Accord",
        yearFrom: 1998,
        yearTo: 2023,
        versions: ["LX", "EX", "EXL", "Touring", "2.0 Turbo", "Hybrid"],
      },
      {
        name: "City",
        yearFrom: 2009,
        yearTo: 2025,
        versions: ["DX", "LX", "EX", "EXL", "Touring", "Hatchback", "Sedan", "1.5"],
      },
      {
        name: "Civic",
        yearFrom: 1992,
        yearTo: 2025,
        versions: [
          "DX",
          "LX",
          "LXS",
          "LXL",
          "LXR",
          "EX",
          "EXL",
          "EXR",
          "Si",
          "Sport",
          "Touring",
          "Type R",
          "Hatchback",
          "Sedan",
          "1.5 Turbo",
          "1.6",
          "1.7",
          "1.8",
          "2.0",
        ],
      },
      {
        name: "CR-V",
        yearFrom: 2000,
        yearTo: 2025,
        versions: ["LX", "EX", "EXL", "Touring", "AWD", "Hybrid", "1.5 Turbo", "2.0", "2.4"],
      },
      { name: "e:NP1", yearFrom: 2024, yearTo: 2025, versions: ["Touring"] },
      {
        name: "Fit",
        yearFrom: 2003,
        yearTo: 2021,
        versions: ["LX", "LXL", "EX", "EXL", "CX", "DX", "Personal", "Twist", "1.4", "1.5"],
      },
      {
        name: "HR-V",
        yearFrom: 2015,
        yearTo: 2025,
        versions: ["LX", "EX", "EXL", "Touring", "Advance", "Sport", "1.5 Turbo", "1.8"],
      },
      {
        name: "WR-V",
        yearFrom: 2017,
        yearTo: 2025,
        versions: ["EX", "EXL", "Touring", "1.5"],
      },
      {
        name: "ZR-V",
        yearFrom: 2024,
        yearTo: 2025,
        versions: ["EXL", "Touring", "2.0 Hybrid"],
      },
    ],
  },

  // ── HYUNDAI ─────────────────────────────────────────────────────────────
  {
    name: "Hyundai",
    models: [
      {
        name: "Azera",
        yearFrom: 2007,
        yearTo: 2020,
        versions: ["GLS", "3.0 V6", "3.3 V6"],
      },
      {
        name: "Creta",
        yearFrom: 2017,
        yearTo: 2025,
        versions: [
          "Action",
          "Attitude",
          "Smart",
          "Comfort",
          "Limited",
          "Launch Edition",
          "Platinum",
          "Ultimate",
          "N Line",
          "1.0 Turbo",
          "1.6",
          "2.0",
        ],
      },
      {
        name: "Elantra",
        yearFrom: 2011,
        yearTo: 2016,
        versions: ["GLS", "Special Edition", "1.8", "2.0"],
      },
      {
        name: "HB20",
        yearFrom: 2012,
        yearTo: 2025,
        versions: [
          "Comfort",
          "Comfort Plus",
          "Premium",
          "Evolution",
          "Platinum",
          "Launch Edition",
          "Limited Edition",
          "Sport",
          "1.0",
          "1.0 Turbo",
          "1.6",
        ],
      },
      {
        name: "HB20S",
        yearFrom: 2013,
        yearTo: 2025,
        versions: [
          "Comfort",
          "Comfort Plus",
          "Premium",
          "Evolution",
          "Platinum",
          "1.0",
          "1.0 Turbo",
          "1.6",
        ],
      },
      {
        name: "HB20X",
        yearFrom: 2014,
        yearTo: 2025,
        versions: ["Style", "Premium", "Evolution", "Diamond Plus", "1.6"],
      },
      {
        name: "i30",
        yearFrom: 2009,
        yearTo: 2019,
        versions: ["GLS", "2.0", "1.8", "1.6"],
      },
      {
        name: "i30 CW",
        yearFrom: 2009,
        yearTo: 2013,
        versions: ["GLS", "2.0"],
      },
      {
        name: "IONIQ 5",
        yearFrom: 2022,
        yearTo: 2025,
        versions: ["Connected", "Creative", "Exclusive"],
      },
      {
        name: "IONIQ 6",
        yearFrom: 2024,
        yearTo: 2025,
        versions: ["Connected", "Creative"],
      },
      {
        name: "ix35",
        yearFrom: 2011,
        yearTo: 2019,
        versions: ["GLS", "GL", "2.0", "Launching Edition"],
      },
      {
        name: "Kona",
        yearFrom: 2022,
        yearTo: 2025,
        versions: ["Electric", "Limited", "Ultimate"],
      },
      {
        name: "New Tucson",
        yearFrom: 2016,
        yearTo: 2025,
        versions: ["GLS", "GL", "Ultimate", "N Line", "Limited", "Platinum", "1.6 Turbo"],
      },
      {
        name: "Santa Fe",
        yearFrom: 2006,
        yearTo: 2025,
        versions: ["GLS", "3.3 V6", "2.4", "Touring", "Limited"],
      },
      {
        name: "Sonata",
        yearFrom: 2004,
        yearTo: 2014,
        versions: ["GLS", "2.4"],
      },
      {
        name: "Tucson",
        yearFrom: 2005,
        yearTo: 2016,
        versions: ["GLS", "GL", "2.0", "2.7 V6"],
      },
      {
        name: "Veloster",
        yearFrom: 2012,
        yearTo: 2019,
        versions: ["1.6", "T-GDi", "N"],
      },
      {
        name: "Veracruz",
        yearFrom: 2007,
        yearTo: 2013,
        versions: ["GLS", "3.8 V6"],
      },
    ],
  },

  // ── JAC ─────────────────────────────────────────────────────────────────
  {
    name: "JAC",
    models: [
      { name: "E-JS1", yearFrom: 2022, yearTo: 2025, versions: ["Elétrico"] },
      { name: "E-J7", yearFrom: 2022, yearTo: 2025, versions: ["Elétrico"] },
      { name: "iEV40", yearFrom: 2020, yearTo: 2022, versions: ["Elétrico"] },
      { name: "iEV60", yearFrom: 2021, yearTo: 2022, versions: ["Elétrico"] },
      { name: "J2", yearFrom: 2012, yearTo: 2017, versions: ["1.4"] },
      { name: "J3", yearFrom: 2011, yearTo: 2016, versions: ["1.4", "Turin"] },
      { name: "J5", yearFrom: 2012, yearTo: 2016, versions: ["1.5"] },
      { name: "J6", yearFrom: 2011, yearTo: 2016, versions: ["2.0"] },
      {
        name: "T40",
        yearFrom: 2018,
        yearTo: 2021,
        versions: ["1.5", "1.6 CVT"],
      },
      { name: "T50", yearFrom: 2018, yearTo: 2021, versions: ["1.5 Turbo"] },
      {
        name: "T60",
        yearFrom: 2019,
        yearTo: 2021,
        versions: ["1.5 Turbo", "CVT"],
      },
      { name: "T80", yearFrom: 2018, yearTo: 2021, versions: ["2.0 Turbo"] },
    ],
  },

  // ── JEEP ────────────────────────────────────────────────────────────────
  {
    name: "Jeep",
    models: [
      {
        name: "Cherokee",
        yearFrom: 2014,
        yearTo: 2023,
        versions: ["Sport", "Longitude", "Limited", "Trailhawk", "Overland", "2.0 Turbo Diesel", "3.2 V6"],
      },
      {
        name: "Commander",
        yearFrom: 2022,
        yearTo: 2025,
        versions: ["Limited", "Overland", "Blackhawk", "TD380 Turbo Diesel", "1.3 Turbo", "2.0 Turbo Diesel"],
      },
      {
        name: "Compass",
        yearFrom: 2017,
        yearTo: 2025,
        versions: [
          "Sport",
          "Longitude",
          "Limited",
          "Trailhawk",
          "S",
          "80 Anos",
          "Blackhawk",
          "4xe",
          "TD350 Turbo Diesel",
          "1.3 Turbo",
          "2.0",
          "2.0 Turbo Diesel",
        ],
      },
      {
        name: "Gladiator",
        yearFrom: 2020,
        yearTo: 2025,
        versions: ["Overland", "Rubicon", "3.6 V6"],
      },
      {
        name: "Grand Cherokee",
        yearFrom: 2005,
        yearTo: 2025,
        versions: [
          "Laredo",
          "Limited",
          "Overland",
          "Summit",
          "Trailhawk",
          "SRT",
          "Trackhawk",
          "L",
          "3.0 Diesel",
          "3.6 V6",
          "5.7 V8",
          "6.4 V8",
        ],
      },
      {
        name: "Renegade",
        yearFrom: 2015,
        yearTo: 2025,
        versions: [
          "Sport",
          "Longitude",
          "Limited",
          "Trailhawk",
          "S",
          "80 Anos",
          "Moab",
          "STD",
          "T270 Turbo",
          "1.0 Turbo",
          "1.3 Turbo",
          "1.8",
          "2.0 Diesel",
        ],
      },
      {
        name: "Wrangler",
        yearFrom: 2007,
        yearTo: 2025,
        versions: ["Sport", "Sahara", "Rubicon", "Unlimited", "4xe", "2.0 Turbo", "3.6 V6"],
      },
    ],
  },

  // ── KIA ─────────────────────────────────────────────────────────────────
  {
    name: "Kia",
    models: [
      {
        name: "Bongo",
        yearFrom: 2006,
        yearTo: 2025,
        versions: ["K-2500", "2.5 Diesel", "Cabine Simples", "Cabine Dupla"],
      },
      {
        name: "Cadenza",
        yearFrom: 2012,
        yearTo: 2020,
        versions: ["EX", "3.5 V6"],
      },
      {
        name: "Carnival",
        yearFrom: 2006,
        yearTo: 2025,
        versions: ["EX", "EX1", "SX", "3.3 V6", "3.5 V6"],
      },
      { name: "Carens", yearFrom: 2007, yearTo: 2014, versions: ["EX", "2.0"] },
      {
        name: "Cerato",
        yearFrom: 2010,
        yearTo: 2025,
        versions: ["SX", "EX", "LX", "1.6", "2.0", "EX2"],
      },
      {
        name: "EV6",
        yearFrom: 2023,
        yearTo: 2025,
        versions: ["EX", "GT-Line", "GT"],
      },
      {
        name: "EV9",
        yearFrom: 2024,
        yearTo: 2025,
        versions: ["EX", "GT-Line"],
      },
      {
        name: "Mohave",
        yearFrom: 2009,
        yearTo: 2015,
        versions: ["EX", "3.8 V6", "3.0 Diesel"],
      },
      {
        name: "Niro",
        yearFrom: 2023,
        yearTo: 2025,
        versions: ["EV", "Hybrid", "PHEV"],
      },
      {
        name: "Optima",
        yearFrom: 2012,
        yearTo: 2019,
        versions: ["EX", "SX", "2.0 Turbo"],
      },
      {
        name: "Picanto",
        yearFrom: 2007,
        yearTo: 2022,
        versions: ["EX", "1.0", "1.1"],
      },
      { name: "Seltos", yearFrom: 2024, yearTo: 2025, versions: ["EX", "SX", "2.0"] },
      {
        name: "Sorento",
        yearFrom: 2005,
        yearTo: 2025,
        versions: ["EX", "EX2", "SX", "2.4", "3.5 V6", "2.2 Diesel", "Hybrid"],
      },
      {
        name: "Soul",
        yearFrom: 2010,
        yearTo: 2022,
        versions: ["EX", "EX2", "1.6"],
      },
      {
        name: "Sportage",
        yearFrom: 2005,
        yearTo: 2025,
        versions: [
          "LX",
          "EX",
          "EX1",
          "EX2",
          "SX",
          "2.0",
          "2.0 Diesel",
          "Hybrid",
        ],
      },
      {
        name: "Stinger",
        yearFrom: 2018,
        yearTo: 2023,
        versions: ["GT", "EX", "3.3 V6 Turbo"],
      },
      { name: "Stonic", yearFrom: 2022, yearTo: 2025, versions: ["EX", "EX1", "1.0 Turbo"] },
    ],
  },

  // ── LAND ROVER ──────────────────────────────────────────────────────────
  {
    name: "Land Rover",
    models: [
      {
        name: "Defender",
        yearFrom: 1990,
        yearTo: 2025,
        versions: ["90", "110", "130", "S", "SE", "HSE", "X", "V8", "2.0 Turbo", "3.0 I6", "5.0 V8"],
      },
      {
        name: "Discovery",
        yearFrom: 2005,
        yearTo: 2025,
        versions: ["SE", "HSE", "HSE Luxury", "S", "R-Dynamic", "2.0 Turbo", "3.0 I6", "3.0 TDV6"],
      },
      {
        name: "Discovery Sport",
        yearFrom: 2015,
        yearTo: 2025,
        versions: ["SE", "HSE", "R-Dynamic", "S", "2.0 Turbo", "2.0 Diesel"],
      },
      {
        name: "Freelander 2",
        yearFrom: 2007,
        yearTo: 2015,
        versions: ["S", "SE", "HSE", "2.2 SD4", "2.0 Si4"],
      },
      {
        name: "Range Rover",
        yearFrom: 2002,
        yearTo: 2025,
        versions: [
          "Vogue",
          "HSE",
          "Autobiography",
          "SV",
          "Sport",
          "Westminster",
          "3.0 I6",
          "4.4 V8",
          "5.0 V8",
        ],
      },
      {
        name: "Range Rover Evoque",
        yearFrom: 2012,
        yearTo: 2025,
        versions: ["Pure", "Prestige", "Dynamic", "SE", "HSE", "R-Dynamic", "2.0 Turbo", "2.0 Diesel"],
      },
      {
        name: "Range Rover Sport",
        yearFrom: 2006,
        yearTo: 2025,
        versions: ["SE", "HSE", "Autobiography", "SVR", "P400e", "P530"],
      },
      {
        name: "Range Rover Velar",
        yearFrom: 2017,
        yearTo: 2025,
        versions: ["S", "SE", "HSE", "R-Dynamic", "2.0 Turbo", "3.0 I6"],
      },
    ],
  },

  // ── LIFAN ───────────────────────────────────────────────────────────────
  {
    name: "Lifan",
    models: [
      { name: "320", yearFrom: 2010, yearTo: 2014, versions: ["1.3"] },
      { name: "530", yearFrom: 2014, yearTo: 2017, versions: ["1.5"] },
      { name: "620", yearFrom: 2010, yearTo: 2014, versions: ["1.6"] },
      {
        name: "X50",
        yearFrom: 2015,
        yearTo: 2018,
        versions: ["1.5 VIP", "1.5 CVT"],
      },
      {
        name: "X60",
        yearFrom: 2013,
        yearTo: 2018,
        versions: ["1.8 VIP", "1.8 CVT"],
      },
      { name: "X80", yearFrom: 2018, yearTo: 2019, versions: ["2.0 Turbo"] },
    ],
  },

  // ── MERCEDES-BENZ ───────────────────────────────────────────────────────
  {
    name: "Mercedes-Benz",
    models: [
      {
        name: "Classe A",
        yearFrom: 1999,
        yearTo: 2025,
        versions: [
          "160",
          "190",
          "200",
          "250",
          "AMG A35",
          "AMG A45",
          "Sedan",
          "Hatch",
        ],
      },
      {
        name: "Classe B",
        yearFrom: 2006,
        yearTo: 2023,
        versions: ["170", "180", "200"],
      },
      {
        name: "Classe C",
        yearFrom: 1994,
        yearTo: 2025,
        versions: [
          "180",
          "200",
          "250",
          "300",
          "350",
          "AMG C43",
          "AMG C63",
          "Coupé",
          "Estate",
          "Avantgarde",
          "AMG Line",
        ],
      },
      {
        name: "Classe E",
        yearFrom: 2002,
        yearTo: 2025,
        versions: [
          "250",
          "300",
          "350",
          "400",
          "AMG E53",
          "AMG E63",
          "Avantgarde",
          "Estate",
          "Cabriolet",
        ],
      },
      {
        name: "Classe S",
        yearFrom: 2006,
        yearTo: 2025,
        versions: ["350", "400", "500", "560", "AMG S63", "AMG S65", "Maybach"],
      },
      {
        name: "CLA",
        yearFrom: 2013,
        yearTo: 2025,
        versions: [
          "180",
          "200",
          "250",
          "AMG CLA35",
          "AMG CLA45",
          "Shooting Brake",
        ],
      },
      {
        name: "CLC",
        yearFrom: 2008,
        yearTo: 2011,
        versions: ["200 Kompressor"],
      },
      {
        name: "CLE",
        yearFrom: 2024,
        yearTo: 2025,
        versions: ["200", "300", "AMG 53", "Coupé", "Cabriolet"],
      },
      {
        name: "CLS",
        yearFrom: 2005,
        yearTo: 2024,
        versions: ["350", "400", "450", "AMG 53", "AMG 63", "Shooting Brake"],
      },
      { name: "EQA", yearFrom: 2022, yearTo: 2025, versions: ["250", "350"] },
      { name: "EQB", yearFrom: 2023, yearTo: 2025, versions: ["250", "350"] },
      { name: "EQC", yearFrom: 2020, yearTo: 2023, versions: ["400"] },
      {
        name: "EQE",
        yearFrom: 2023,
        yearTo: 2025,
        versions: ["350", "500", "AMG"],
      },
      {
        name: "EQS",
        yearFrom: 2022,
        yearTo: 2025,
        versions: ["450", "580", "AMG", "SUV"],
      },
      {
        name: "GLA",
        yearFrom: 2015,
        yearTo: 2025,
        versions: ["200", "250", "AMG GLA35", "AMG GLA45", "Vision"],
      },
      {
        name: "GLB",
        yearFrom: 2020,
        yearTo: 2025,
        versions: ["200", "250", "AMG GLB35"],
      },
      {
        name: "GLC",
        yearFrom: 2016,
        yearTo: 2025,
        versions: ["200", "250", "300", "AMG GLC43", "AMG GLC63", "Coupé"],
      },
      {
        name: "GLE",
        yearFrom: 2012,
        yearTo: 2025,
        versions: ["350", "400", "450", "AMG GLE53", "AMG GLE63", "Coupé"],
      },
      {
        name: "GLS",
        yearFrom: 2016,
        yearTo: 2025,
        versions: ["350", "450", "580", "AMG GLS63", "Maybach"],
      },
      {
        name: "SLC",
        yearFrom: 2016,
        yearTo: 2020,
        versions: ["180", "200", "300", "AMG SLC43"],
      },
      {
        name: "SL",
        yearFrom: 2012,
        yearTo: 2025,
        versions: ["400", "450", "500", "AMG SL55", "AMG SL63"],
      },
      {
        name: "Sprinter",
        yearFrom: 2003,
        yearTo: 2025,
        versions: [
          "310",
          "311",
          "313",
          "314",
          "415",
          "416",
          "515",
          "516",
          "Furgão",
          "Chassis",
        ],
      },
      {
        name: "Vito",
        yearFrom: 2003,
        yearTo: 2025,
        versions: ["111", "113", "119", "Tourer"],
      },
      {
        name: "AMG GT",
        yearFrom: 2016,
        yearTo: 2025,
        versions: ["S", "R", "C", "Black Series", "4-Door"],
      },
    ],
  },

  // ── MINI ────────────────────────────────────────────────────────────────
  {
    name: "Mini",
    models: [
      {
        name: "Cooper",
        yearFrom: 2002,
        yearTo: 2025,
        versions: ["S", "SE", "JCW", "Hatch", "Convertible"],
      },
      {
        name: "Cooper S",
        yearFrom: 2002,
        yearTo: 2025,
        versions: ["Hatch", "Convertible", "JCW"],
      },
      {
        name: "Countryman",
        yearFrom: 2011,
        yearTo: 2025,
        versions: ["Cooper", "Cooper S", "Cooper SE", "JCW", "ALL4"],
      },
      {
        name: "Clubman",
        yearFrom: 2008,
        yearTo: 2024,
        versions: ["Cooper", "Cooper S", "JCW", "ALL4"],
      },
      {
        name: "Paceman",
        yearFrom: 2013,
        yearTo: 2016,
        versions: ["Cooper", "Cooper S", "JCW"],
      },
    ],
  },

  // ── MITSUBISHI ──────────────────────────────────────────────────────────
  {
    name: "Mitsubishi",
    models: [
      {
        name: "ASX",
        yearFrom: 2011,
        yearTo: 2025,
        versions: ["2.0", "AWD", "HPE", "GLS", "1.6 Turbo"],
      },
      {
        name: "Eclipse Cross",
        yearFrom: 2018,
        yearTo: 2025,
        versions: ["HPE", "HPE-S", "GLS", "PHEV", "1.5 Turbo"],
      },
      {
        name: "L200",
        yearFrom: 1999,
        yearTo: 2025,
        versions: [
          "GL",
          "GLS",
          "GLX",
          "Outdoor",
          "Triton",
          "Savana",
          "HPE",
          "HPE-S",
          "Athlete",
          "2.4 Diesel",
          "2.5 Diesel",
          "3.2 Diesel",
          "3.5 V6",
        ],
      },
      {
        name: "Lancer",
        yearFrom: 2003,
        yearTo: 2019,
        versions: ["GT", "HL", "HLE", "2.0", "Evo X"],
      },
      {
        name: "Outlander",
        yearFrom: 2007,
        yearTo: 2025,
        versions: [
          "2.0",
          "2.4",
          "3.0 V6",
          "HPE",
          "HPE-S",
          "Sport",
          "PHEV",
          "GLS",
        ],
      },
      {
        name: "Outlander Sport",
        yearFrom: 2012,
        yearTo: 2019,
        versions: ["HPE", "HPE-S", "2.0"],
      },
      {
        name: "Pajero",
        yearFrom: 1998,
        yearTo: 2021,
        versions: ["Full", "GLS", "HPE", "3.2 Diesel", "3.8 V6"],
      },
      {
        name: "Pajero Dakar",
        yearFrom: 2010,
        yearTo: 2019,
        versions: ["HPE", "3.2 Diesel", "3.5 V6 Flex"],
      },
      {
        name: "Pajero Sport",
        yearFrom: 2005,
        yearTo: 2025,
        versions: ["GLS", "HPE", "HPE-S", "2.4 Diesel", "R"],
      },
      {
        name: "Pajero TR4",
        yearFrom: 2007,
        yearTo: 2015,
        versions: ["2.0", "4x2", "4x4", "Flex"],
      },
    ],
  },

  // ── NISSAN ──────────────────────────────────────────────────────────────
  {
    name: "Nissan",
    models: [
      {
        name: "Frontier",
        yearFrom: 2002,
        yearTo: 2025,
        versions: [
          "XE",
          "SE",
          "LE",
          "SV",
          "Attack",
          "PRO-4X",
          "Platinum",
          "2.3 Diesel",
          "2.5",
          "2.5 Diesel",
        ],
      },
      {
        name: "Grand Livina",
        yearFrom: 2009,
        yearTo: 2014,
        versions: ["S", "SL", "1.8"],
      },
      {
        name: "Kicks",
        yearFrom: 2017,
        yearTo: 2025,
        versions: [
          "S",
          "SV",
          "SL",
          "Special Edition",
          "Advance",
          "Exclusive",
          "e-Power",
          "1.6",
        ],
      },
      { name: "Leaf", yearFrom: 2019, yearTo: 2024, versions: ["Elétrico"] },
      {
        name: "Livina",
        yearFrom: 2009,
        yearTo: 2014,
        versions: ["S", "SL", "Night & Day", "1.6", "1.8"],
      },
      {
        name: "March",
        yearFrom: 2011,
        yearTo: 2021,
        versions: ["S", "SV", "SL", "1.0", "1.6"],
      },
      {
        name: "Pathfinder",
        yearFrom: 2001,
        yearTo: 2014,
        versions: ["SE", "LE", "4.0 V6"],
      },
      {
        name: "Sentra",
        yearFrom: 2007,
        yearTo: 2025,
        versions: ["S", "SV", "SL", "2.0", "Advance", "Exclusive", "1.8"],
      },
      {
        name: "Tiida",
        yearFrom: 2008,
        yearTo: 2014,
        versions: ["S", "SL", "1.8", "Hatch", "Sedan"],
      },
      {
        name: "Versa",
        yearFrom: 2012,
        yearTo: 2025,
        versions: [
          "S",
          "SV",
          "SL",
          "1.0",
          "1.6",
          "Advance",
          "Exclusive",
          "Sense",
        ],
      },
      {
        name: "X-Trail",
        yearFrom: 2004,
        yearTo: 2018,
        versions: ["SE", "SL", "2.5", "2.0"],
      },
    ],
  },

  // ── PEUGEOT ─────────────────────────────────────────────────────────────
  {
    name: "Peugeot",
    models: [
      {
        name: "2008",
        yearFrom: 2015,
        yearTo: 2025,
        versions: ["Allure", "Griffe", "GT", "Business", "Style", "Crossway", "1.6", "1.6 THP"],
      },
      {
        name: "206",
        yearFrom: 2000,
        yearTo: 2008,
        versions: [
          "Soleil",
          "Selection",
          "Presence",
          "Feline",
          "Rallye",
          "1.0",
          "1.4",
          "1.6",
          "SW",
        ],
      },
      {
        name: "207",
        yearFrom: 2008,
        yearTo: 2015,
        versions: [
          "XR",
          "XS",
          "Quiksilver",
          "Passion",
          "SW",
          "Hatch",
          "Sedan",
          "Escapade",
          "1.4",
          "1.6",
        ],
      },
      {
        name: "208",
        yearFrom: 2013,
        yearTo: 2025,
        versions: [
          "Active",
          "Allure",
          "Griffe",
          "GT",
          "Active Pack",
          "Style",
          "Roadtrip",
          "1.2 Turbo",
          "1.6",
        ],
      },
      {
        name: "3008",
        yearFrom: 2011,
        yearTo: 2025,
        versions: ["Allure", "Griffe", "GT", "1.6 THP"],
      },
      {
        name: "301",
        yearFrom: 2013,
        yearTo: 2017,
        versions: ["Allure", "1.6"],
      },
      {
        name: "307",
        yearFrom: 2002,
        yearTo: 2012,
        versions: [
          "Presence",
          "Feline",
          "Rallye",
          "SW",
          "Sedan",
          "Hatch",
          "1.6",
          "2.0",
        ],
      },
      {
        name: "308",
        yearFrom: 2012,
        yearTo: 2019,
        versions: ["Active", "Allure", "Griffe", "Roland Garros", "1.6 THP"],
      },
      {
        name: "408",
        yearFrom: 2011,
        yearTo: 2019,
        versions: ["Allure", "Griffe", "Feline", "Business", "1.6 THP", "2.0"],
      },
      {
        name: "5008",
        yearFrom: 2018,
        yearTo: 2025,
        versions: ["Allure", "Griffe", "GT", "1.6 THP"],
      },
      {
        name: "508",
        yearFrom: 2013,
        yearTo: 2019,
        versions: ["Allure", "Griffe", "1.6 THP"],
      },
      {
        name: "Boxer",
        yearFrom: 2010,
        yearTo: 2025,
        versions: ["Furgão", "Chassi", "Minibus", "2.0 Diesel", "2.2 Diesel"],
      },
      {
        name: "Expert",
        yearFrom: 2018,
        yearTo: 2025,
        versions: ["Premium", "Business", "Furgão", "1.6 Turbo Diesel"],
      },
      {
        name: "Hoggar",
        yearFrom: 2010,
        yearTo: 2014,
        versions: ["X-Line", "Escapade", "1.4", "1.6"],
      },
      {
        name: "Partner",
        yearFrom: 2003,
        yearTo: 2019,
        versions: ["Furgão", "1.6"],
      },
      { name: "e-208", yearFrom: 2022, yearTo: 2025, versions: ["GT"] },
      { name: "e-2008", yearFrom: 2023, yearTo: 2025, versions: ["GT"] },
      {
        name: "Landtrek",
        yearFrom: 2023,
        yearTo: 2025,
        versions: ["Allure", "Active", "1.9 Diesel"],
      },
    ],
  },

  // ── PORSCHE ─────────────────────────────────────────────────────────────
  {
    name: "Porsche",
    models: [
      {
        name: "718 Boxster",
        yearFrom: 2017,
        yearTo: 2025,
        versions: ["2.0", "S", "GTS", "Spyder"],
      },
      {
        name: "718 Cayman",
        yearFrom: 2017,
        yearTo: 2025,
        versions: ["2.0", "S", "GTS", "GT4"],
      },
      {
        name: "911",
        yearFrom: 1999,
        yearTo: 2025,
        versions: [
          "Carrera",
          "Carrera S",
          "Carrera 4S",
          "Turbo",
          "Turbo S",
          "GT3",
          "GT3 RS",
          "Targa",
          "Cabriolet",
        ],
      },
      {
        name: "Boxster",
        yearFrom: 1997,
        yearTo: 2016,
        versions: ["2.7", "S", "GTS", "Spyder"],
      },
      {
        name: "Cayenne",
        yearFrom: 2003,
        yearTo: 2025,
        versions: ["3.6", "S", "GTS", "Turbo", "Turbo S", "E-Hybrid", "Coupé"],
      },
      {
        name: "Cayman",
        yearFrom: 2006,
        yearTo: 2016,
        versions: ["2.7", "S", "GTS", "GT4"],
      },
      {
        name: "Macan",
        yearFrom: 2015,
        yearTo: 2025,
        versions: ["2.0", "S", "GTS", "Turbo", "Electric"],
      },
      {
        name: "Panamera",
        yearFrom: 2010,
        yearTo: 2025,
        versions: [
          "4",
          "4S",
          "GTS",
          "Turbo",
          "Turbo S",
          "E-Hybrid",
          "Sport Turismo",
        ],
      },
      {
        name: "Taycan",
        yearFrom: 2020,
        yearTo: 2025,
        versions: ["4S", "GTS", "Turbo", "Turbo S", "Cross Turismo"],
      },
    ],
  },

  // ── RAM ─────────────────────────────────────────────────────────────────
  {
    name: "RAM",
    models: [
      {
        name: "1500",
        yearFrom: 2012,
        yearTo: 2025,
        versions: ["Laramie", "Limited", "Rebel", "R/T", "Classic", "3.6 V6", "5.7 V8"],
      },
      {
        name: "2500",
        yearFrom: 2012,
        yearTo: 2025,
        versions: ["Laramie", "Limited", "6.7 Cummins"],
      },
      {
        name: "3500",
        yearFrom: 2019,
        yearTo: 2025,
        versions: ["Laramie", "Limited", "6.7 Cummins"],
      },
      {
        name: "Rampage",
        yearFrom: 2024,
        yearTo: 2025,
        versions: ["Rebel", "Laramie", "R/T", "2.0 Turbo Diesel"],
      },
    ],
  },

  // ── RENAULT ─────────────────────────────────────────────────────────────
  {
    name: "Renault",
    models: [
      {
        name: "Captur",
        yearFrom: 2017,
        yearTo: 2025,
        versions: ["Life", "Zen", "Intense", "Bose", "Iconic", "1.3 Turbo", "1.6", "2.0"],
      },
      {
        name: "Clio",
        yearFrom: 1996,
        yearTo: 2016,
        versions: [
          "RL",
          "RN",
          "RT",
          "1.0",
          "1.6",
          "Authentique",
          "Expression",
          "Privilège",
        ],
      },
      {
        name: "Duster",
        yearFrom: 2012,
        yearTo: 2025,
        versions: [
          "Expression",
          "Dynamique",
          "Iconic",
          "Intense",
          "Zen",
          "Life",
          "1.6",
          "2.0",
          "1.3 Turbo",
          "4x2",
          "4x4",
        ],
      },
      {
        name: "Duster Oroch",
        yearFrom: 2016,
        yearTo: 2025,
        versions: ["Expression", "Dynamique", "Iconic", "Intense", "1.6", "2.0"],
      },
      {
        name: "Fluence",
        yearFrom: 2011,
        yearTo: 2017,
        versions: ["Expression", "Dynamique", "Privilège", "2.0", "GT Line"],
      },
      {
        name: "Kangoo",
        yearFrom: 2000,
        yearTo: 2017,
        versions: ["RL", "RN", "1.0", "1.6", "Express"],
      },
      {
        name: "Kardian",
        yearFrom: 2024,
        yearTo: 2025,
        versions: ["Evolution", "Intense", "Iconic", "Première Edition", "1.0 Turbo"],
      },
      {
        name: "Kwid",
        yearFrom: 2017,
        yearTo: 2025,
        versions: ["Life", "Zen", "Intense", "Outsider", "1.0"],
      },
      {
        name: "Logan",
        yearFrom: 2007,
        yearTo: 2020,
        versions: ["Expression", "Authentique", "Dynamique", "1.0", "1.6"],
      },
      {
        name: "Master",
        yearFrom: 2003,
        yearTo: 2025,
        versions: ["Furgão", "Chassis", "Minibus", "2.3 dCi"],
      },
      {
        name: "Mégane",
        yearFrom: 1998,
        yearTo: 2016,
        versions: ["RT", "Expression", "Dynamique", "Grand Tour", "2.0"],
      },
      {
        name: "Oroch",
        yearFrom: 2016,
        yearTo: 2025,
        versions: ["Expression", "Dynamique", "Iconic", "Intense", "1.6", "2.0"],
      },
      {
        name: "Sandero",
        yearFrom: 2008,
        yearTo: 2022,
        versions: [
          "Expression",
          "Authentique",
          "Dynamique",
          "Privilège",
          "Stepway",
          "RS",
          "1.0",
          "1.6",
          "Zen",
          "Intense",
          "Life",
        ],
      },
      {
        name: "Scénic",
        yearFrom: 2001,
        yearTo: 2010,
        versions: ["RT", "Privilège", "Expression", "1.6", "2.0"],
      },
      {
        name: "Symbol",
        yearFrom: 2009,
        yearTo: 2014,
        versions: ["Expression", "Privilège", "1.6"],
      },
      {
        name: "Zoe",
        yearFrom: 2020,
        yearTo: 2024,
        versions: ["Life", "Zen", "Intense", "R110", "R135"],
      },
    ],
  },

  // ── SUBARU ──────────────────────────────────────────────────────────────
  {
    name: "Subaru",
    models: [
      {
        name: "Crosstrek",
        yearFrom: 2023,
        yearTo: 2025,
        versions: ["2.0i-S", "Limited"],
      },
      {
        name: "Forester",
        yearFrom: 2009,
        yearTo: 2025,
        versions: ["2.0", "XT", "S-Edition", "Sport"],
      },
      {
        name: "Impreza",
        yearFrom: 2001,
        yearTo: 2024,
        versions: ["2.0", "WRX", "Hatch", "Sedan"],
      },
      {
        name: "Legacy",
        yearFrom: 2005,
        yearTo: 2021,
        versions: ["2.0", "2.5", "Outback"],
      },
      {
        name: "Outback",
        yearFrom: 2004,
        yearTo: 2025,
        versions: ["2.5", "3.6", "XT", "Limited"],
      },
      {
        name: "WRX",
        yearFrom: 2002,
        yearTo: 2025,
        versions: ["2.0 Turbo", "STI", "Limited"],
      },
      {
        name: "XV",
        yearFrom: 2012,
        yearTo: 2023,
        versions: ["2.0", "2.0i-S", "S-Edition"],
      },
      { name: "Solterra", yearFrom: 2023, yearTo: 2025, versions: ["Limited"] },
    ],
  },

  // ── SUZUKI ──────────────────────────────────────────────────────────────
  {
    name: "Suzuki",
    models: [
      {
        name: "Grand Vitara",
        yearFrom: 2006,
        yearTo: 2016,
        versions: ["2.0", "4x2", "4x4", "AT"],
      },
      {
        name: "Jimny",
        yearFrom: 2012,
        yearTo: 2025,
        versions: ["4All", "4Sport", "4Style", "Sierra", "1.3", "1.5"],
      },
      {
        name: "S-Cross",
        yearFrom: 2016,
        yearTo: 2024,
        versions: ["GLS", "GLX", "4Sport", "4Style", "1.4 Turbo", "1.6"],
      },
      {
        name: "Swift",
        yearFrom: 2005,
        yearTo: 2019,
        versions: ["1.4", "1.5", "Sport"],
      },
      {
        name: "SX4",
        yearFrom: 2009,
        yearTo: 2015,
        versions: ["2.0", "S-Cross", "4x4"],
      },
      {
        name: "Vitara",
        yearFrom: 2015,
        yearTo: 2025,
        versions: ["4You", "4Sport", "4Style", "Hybrid", "1.4 Turbo", "1.6"],
      },
    ],
  },

  // ── TOYOTA ──────────────────────────────────────────────────────────────
  {
    name: "Toyota",
    models: [
      {
        name: "Bandeirante",
        yearFrom: 1958,
        yearTo: 2001,
        versions: ["OJ", "BJ", "Jipe", "Pick-up"],
      },
      {
        name: "Camry",
        yearFrom: 2004,
        yearTo: 2025,
        versions: ["XLE", "3.5 V6", "2.5", "Hybrid"],
      },
      {
        name: "Corolla",
        yearFrom: 1992,
        yearTo: 2025,
        versions: [
          "XEi",
          "XLi",
          "GLi",
          "SEG",
          "Altis",
          "XRS",
          "Hybrid",
          "GR-S",
          "GR Sport",
          "1.8",
          "2.0",
        ],
      },
      {
        name: "Corolla Cross",
        yearFrom: 2021,
        yearTo: 2025,
        versions: ["XRE", "XRX", "XRV", "Hybrid", "GR-S", "1.8", "2.0"],
      },
      {
        name: "Etios",
        yearFrom: 2013,
        yearTo: 2021,
        versions: ["X", "XS", "XLS", "Platinum", "Cross", "Hatch", "Sedan", "1.3", "1.5"],
      },
      {
        name: "GR Corolla",
        yearFrom: 2024,
        yearTo: 2025,
        versions: ["Core", "Circuit Edition", "1.6 Turbo"],
      },
      {
        name: "GR Supra",
        yearFrom: 2020,
        yearTo: 2025,
        versions: ["3.0", "2.0", "A91"],
      },
      { name: "GR Yaris", yearFrom: 2024, yearTo: 2025, versions: ["1.6 Turbo"] },
      {
        name: "Hilux",
        yearFrom: 1992,
        yearTo: 2025,
        versions: [
          "STD",
          "SR",
          "SRV",
          "SRX",
          "GR-S",
          "Cabine Simples",
          "Cabine Dupla",
          "Low",
          "High",
          "4x2",
          "4x4",
          "Diesel",
          "Flex",
          "2.7",
          "2.8 Diesel",
          "3.0 Diesel",
        ],
      },
      {
        name: "Hilux SW4",
        yearFrom: 2005,
        yearTo: 2025,
        versions: ["SR", "SRV", "SRX", "Diamond", "GR-S", "Diesel", "2.7", "2.8 Diesel", "3.0 Diesel"],
      },
      {
        name: "Land Cruiser Prado",
        yearFrom: 2003,
        yearTo: 2025,
        versions: ["VX", "TX", "3.0 Diesel", "2.8 Diesel", "4.0 V6"],
      },
      {
        name: "Prius",
        yearFrom: 2013,
        yearTo: 2025,
        versions: ["Hybrid", "1.8", "2.0"],
      },
      {
        name: "RAV4",
        yearFrom: 2006,
        yearTo: 2025,
        versions: ["2.0", "2.5", "4x2", "4x4", "Hybrid", "SX", "S Connect"],
      },
      {
        name: "Yaris",
        yearFrom: 2018,
        yearTo: 2023,
        versions: ["XL", "XL Plus", "XS", "XLS", "Hatch", "Sedan", "1.3", "1.5"],
      },
      {
        name: "bZ4X",
        yearFrom: 2024,
        yearTo: 2025,
        versions: ["Beyond", "Special Edition"],
      },
    ],
  },

  // ── TROLLER ─────────────────────────────────────────────────────────────
  {
    name: "Troller",
    models: [
      {
        name: "T4",
        yearFrom: 2001,
        yearTo: 2024,
        versions: ["3.2 Diesel", "XLT", "TDI"],
      },
    ],
  },

  // ── VOLKSWAGEN ──────────────────────────────────────────────────────────
  {
    name: "Volkswagen",
    models: [
      {
        name: "Amarok",
        yearFrom: 2010,
        yearTo: 2025,
        versions: [
          "S",
          "SE",
          "Trendline",
          "Highline",
          "Extreme",
          "Comfortline",
          "V6",
          "CD",
          "CS",
          "2.0 TDI",
          "3.0 V6 TDI",
        ],
      },
      {
        name: "Bora",
        yearFrom: 2001,
        yearTo: 2011,
        versions: ["2.0", "1.8 Turbo"],
      },
      { name: "CrossFox", yearFrom: 2005, yearTo: 2016, versions: ["1.6"] },
      {
        name: "Fox",
        yearFrom: 2004,
        yearTo: 2021,
        versions: [
          "City",
          "Plus",
          "Route",
          "Highline",
          "Comfortline",
          "Trendline",
          "Pepper",
          "Run",
          "Connect",
          "Extreme",
          "1.0",
          "1.6",
        ],
      },
      {
        name: "Fusca",
        yearFrom: 1959,
        yearTo: 1996,
        versions: ["1300", "1500", "1600"],
      },
      {
        name: "Gol",
        yearFrom: 1980,
        yearTo: 2024,
        versions: [
          "CL",
          "GL",
          "GTI",
          "MI",
          "Special",
          "City",
          "Power",
          "Trend",
          "Rallye",
          "Comfortline",
          "Trendline",
          "1.0",
          "1.6",
          "G3",
          "G4",
          "G5",
          "G6",
          "G7",
          "G8",
          "Last Edition",
        ],
      },
      {
        name: "Golf",
        yearFrom: 1999,
        yearTo: 2023,
        versions: [
          "1.6",
          "2.0",
          "GTI",
          "GLX",
          "Comfortline",
          "Highline",
          "TSI",
          "Variant",
          "R",
          "R-Line",
        ],
      },
      { name: "ID.4", yearFrom: 2024, yearTo: 2025, versions: ["Pro", "GTX"] },
      { name: "ID.Buzz", yearFrom: 2024, yearTo: 2025, versions: ["Pro"] },
      {
        name: "Jetta",
        yearFrom: 2005,
        yearTo: 2025,
        versions: [
          "2.5",
          "Comfortline",
          "Highline",
          "GLI",
          "R-Line",
          "TSI",
          "Tiptronic",
          "1.4 TSI",
          "2.0 TSI",
        ],
      },
      {
        name: "Nivus",
        yearFrom: 2020,
        yearTo: 2025,
        versions: ["Comfortline", "Highline", "Launching Edition", "200 TSI"],
      },
      {
        name: "Passat",
        yearFrom: 2006,
        yearTo: 2019,
        versions: ["2.0 TSI", "Variant", "Comfortline", "Highline"],
      },
      {
        name: "Polo",
        yearFrom: 2002,
        yearTo: 2025,
        versions: [
          "1.0",
          "1.4",
          "1.6",
          "Hatch",
          "Sedan",
          "Classic",
          "Sportline",
          "Comfortline",
          "Highline",
          "GTS",
          "Track",
          "TSI",
          "200 TSI",
          "Beats",
        ],
      },
      {
        name: "Saveiro",
        yearFrom: 1982,
        yearTo: 2025,
        versions: [
          "CL",
          "City",
          "Plus",
          "Cross",
          "Trooper",
          "Trendline",
          "Highline",
          "Robust",
          "Pepper",
          "1.6",
          "Cabine Simples",
          "Cabine Dupla",
          "Cabine Estendida",
        ],
      },
      {
        name: "SpaceFox",
        yearFrom: 2006,
        yearTo: 2018,
        versions: ["Sportline", "Comfortline", "Highline", "Route", "1.6"],
      },
      {
        name: "T-Cross",
        yearFrom: 2019,
        yearTo: 2025,
        versions: ["200 TSI", "Comfortline", "Highline", "Sense", "1.0 TSI", "1.4 TSI"],
      },
      {
        name: "Taos",
        yearFrom: 2021,
        yearTo: 2025,
        versions: [
          "Comfortline",
          "Highline",
          "Launch Edition",
          "Exclusive",
          "R-Line",
          "1.4 TSI",
        ],
      },
      {
        name: "Tiguan",
        yearFrom: 2009,
        yearTo: 2025,
        versions: ["2.0 TSI", "Comfortline", "Highline", "R-Line", "Allspace"],
      },
      {
        name: "Touareg",
        yearFrom: 2004,
        yearTo: 2018,
        versions: ["3.6 V6", "V8", "TDI"],
      },
      {
        name: "Up!",
        yearFrom: 2014,
        yearTo: 2021,
        versions: [
          "Take",
          "Move",
          "High",
          "Speed",
          "Cross",
          "Connect",
          "Pepper",
          "TSI",
          "1.0",
        ],
      },
      {
        name: "Virtus",
        yearFrom: 2018,
        yearTo: 2025,
        versions: [
          "200 TSI",
          "Comfortline",
          "Highline",
          "GTS",
          "Exclusive",
          "Beats",
        ],
      },
      {
        name: "Voyage",
        yearFrom: 2008,
        yearTo: 2024,
        versions: [
          "1.0",
          "1.6",
          "City",
          "Comfortline",
          "Trendline",
          "Evidence",
        ],
      },
    ],
  },

  // ── VOLVO ───────────────────────────────────────────────────────────────
  {
    name: "Volvo",
    models: [
      { name: "C30", yearFrom: 2007, yearTo: 2013, versions: ["2.0", "T5"] },
      {
        name: "C40",
        yearFrom: 2022,
        yearTo: 2025,
        versions: ["Recharge", "Twin", "Plus", "Ultimate"],
      },
      {
        name: "EX30",
        yearFrom: 2024,
        yearTo: 2025,
        versions: ["Single Motor", "Twin Motor", "Plus", "Ultra"],
      },
      {
        name: "EX90",
        yearFrom: 2024,
        yearTo: 2025,
        versions: ["Plus", "Ultra", "Twin Motor"],
      },
      { name: "S40", yearFrom: 2004, yearTo: 2012, versions: ["2.4", "T5"] },
      {
        name: "S60",
        yearFrom: 2001,
        yearTo: 2025,
        versions: [
          "2.0T",
          "2.5T",
          "T4",
          "T5",
          "T6",
          "T8",
          "Momentum",
          "R-Design",
          "Inscription",
          "Recharge",
        ],
      },
      {
        name: "S80",
        yearFrom: 1999,
        yearTo: 2016,
        versions: ["2.4", "T5", "T6", "V8"],
      },
      {
        name: "S90",
        yearFrom: 2017,
        yearTo: 2025,
        versions: ["T5", "T6", "T8", "Momentum", "Inscription", "Recharge"],
      },
      {
        name: "V40",
        yearFrom: 2013,
        yearTo: 2019,
        versions: [
          "T3",
          "T4",
          "T5",
          "Cross Country",
          "Momentum",
          "R-Design",
          "Inscription",
        ],
      },
      {
        name: "V60",
        yearFrom: 2011,
        yearTo: 2025,
        versions: [
          "T4",
          "T5",
          "T6",
          "Cross Country",
          "Momentum",
          "R-Design",
          "Inscription",
        ],
      },
      {
        name: "V90",
        yearFrom: 2017,
        yearTo: 2025,
        versions: ["T6", "Cross Country", "Momentum", "Inscription"],
      },
      {
        name: "XC40",
        yearFrom: 2018,
        yearTo: 2025,
        versions: [
          "T4",
          "T5",
          "Momentum",
          "R-Design",
          "Inscription",
          "Recharge",
          "Plus",
          "Ultimate",
        ],
      },
      {
        name: "XC60",
        yearFrom: 2009,
        yearTo: 2025,
        versions: [
          "T5",
          "T6",
          "T8",
          "D5",
          "Momentum",
          "R-Design",
          "Inscription",
          "Ultimate",
          "Recharge",
        ],
      },
      {
        name: "XC90",
        yearFrom: 2003,
        yearTo: 2025,
        versions: [
          "T5",
          "T6",
          "T8",
          "D5",
          "Momentum",
          "R-Design",
          "Inscription",
          "Ultimate",
          "Recharge",
        ],
      },
    ],
  },
];

// ---------------------------------------------------------------------------
// Helpers para consulta rápida (cascata)
// ---------------------------------------------------------------------------
// Lookup caches pré-computados na inicialização do módulo (O(1) em vez de O(n))
// ---------------------------------------------------------------------------

const _brandMap = new Map<string, VehicleBrand>();
const _brandNames: string[] = [];

// Inicializa caches uma única vez
(function initCaches() {
  for (const brand of VEHICLE_CATALOG) {
    _brandMap.set(brand.name.toLowerCase(), brand);
  }
  _brandNames.push(
    ...VEHICLE_CATALOG.map((b) => b.name).sort((a, b) =>
      a.localeCompare(b, "pt-BR"),
    ),
  );
})();

// ---------------------------------------------------------------------------

/** Retorna a lista de marcas disponíveis (ordenada) — O(1) cached */
export function getVehicleBrands(): string[] {
  return _brandNames;
}

/** Retorna os modelos para uma marca específica (ordenados) */
export function getModelsForBrand(brand: string): string[] {
  const b = _brandMap.get(brand.toLowerCase());
  if (!b) return [];
  return [...new Set(b.models.map((m) => m.name))].sort((a, b) =>
    a.localeCompare(b, "pt-BR"),
  );
}

/** Retorna o intervalo de anos disponível para um modelo de uma marca */
export function getYearsForModel(brand: string, model: string): number[] {
  const b = _brandMap.get(brand.toLowerCase());
  if (!b) return [];
  const ml = model.toLowerCase();
  const m = b.models.find((v) => v.name.toLowerCase() === ml);
  if (!m) return [];
  const years: number[] = [];
  for (let y = m.yearFrom; y <= m.yearTo; y++) {
    years.push(y);
  }
  return years;
}

/** Retorna as versões disponíveis para uma combinação de marca+modelo */
export function getVersionsForModel(brand: string, model: string): string[] {
  const b = _brandMap.get(brand.toLowerCase());
  if (!b) return [];
  const ml = model.toLowerCase();
  const m = b.models.find((v) => v.name.toLowerCase() === ml);
  if (!m) return [];
  return m.versions
    .filter((v) => v !== "")
    .sort((a, b) => a.localeCompare(b, "pt-BR"));
}
