import type {
  NfeDraftResponse,
  NfeDraftItem,
} from "../../../app/interfaces/nfe.interface";
import type { CompanyFiscalConfig } from "../../../app/interfaces/company-fiscal.interface";

/**
 * Builders de fixtures para testes do módulo SEFAZ direto.
 * Mantemos defaults realistas (UF=SP, regime=SIMPLES) e exposamos overrides
 * para cenários específicos.
 */

export function makeConfig(
  overrides: Partial<CompanyFiscalConfig> = {},
): CompanyFiscalConfig {
  return {
    id: "cfg-test",
    userId: "user-test",
    cnpj: "11222333000181",
    razaoSocial: "EMPRESA TESTE LTDA",
    nomeFantasia: "EMPRESA TESTE",
    inscricaoEstadual: "123456789",
    inscricaoMunicipal: null,
    regimeTributario: "SIMPLES",
    cnae: null,
    ambiente: "HOMOLOGACAO",
    cep: "01000000",
    logradouro: "RUA TESTE",
    numero: "100",
    complemento: null,
    bairro: "CENTRO",
    municipio: "SAO PAULO",
    codMunicipio: "3550308",
    uf: "SP",
    codPais: "1058",
    pais: "BRASIL",
    certificadoPath: null,
    certificadoSenhaEnc: null,
    certificadoValidoAte: null,
    providerName: "SEFAZ_DIRECT",
    providerToken: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    ...overrides,
  } as CompanyFiscalConfig;
}

export function makeItem(
  overrides: Partial<NfeDraftItem> = {},
): NfeDraftItem {
  return {
    id: "item-1",
    productId: null,
    numero: 1,
    codigo: "PROD-001",
    descricao: "PRODUTO TESTE",
    ncm: "87089990",
    cfop: "5102",
    cest: null,
    origem: 0,
    unidade: "UN",
    quantidade: 1,
    valorUnitario: 100,
    valorTotal: 100,
    desconto: null,
    observacoes: null,
    cstIcms: "102",
    cstPis: "49",
    cstCofins: "49",
    aliquotaIcms: null,
    aliquotaIpi: null,
    aliquotaPis: null,
    aliquotaCofins: null,
    reducaoBcIcms: null,
    tributosJson: {
      bcIcms: 0,
      valorIcms: 0,
      aliquotaIcms: 0,
      bcIpi: 0,
      valorIpi: 0,
      aliquotaIpi: 0,
      bcPis: 0,
      valorPis: 0,
      aliquotaPis: 0,
      bcCofins: 0,
      valorCofins: 0,
      aliquotaCofins: 0,
      valorTotalTributos: 0,
    },
    ...overrides,
  };
}

export function makeDraft(
  overrides: Partial<NfeDraftResponse> = {},
): NfeDraftResponse {
  return {
    id: "nfe-test",
    userId: "user-test",
    orderId: null,
    customerId: null,
    ambiente: "HOMOLOGACAO",
    modelo: "55",
    serie: 1,
    numero: 1,
    chaveAcesso: null,
    tipoOperacao: "SAIDA",
    finalidade: "NORMAL",
    destinoOperacao: "INTERNA",
    naturezaOperacao: "VENDA DE MERCADORIA",
    indPresenca: "PRESENCIAL",
    intermediador: null,
    numeroPedido: null,
    informacoesComplementares: null,
    dataEmissao: null,
    dataSaida: null,
    destinatarioJson: {
      tipoPessoa: "PJ",
      cpfCnpj: "00000000000100",
      nome: "CLIENTE TESTE LTDA",
      inscricaoEstadual: "ISENTO",
      email: null,
      telefone: null,
      cep: "04000000",
      logradouro: "AV CLIENTE",
      numero: "200",
      complemento: null,
      bairro: "VILA",
      municipio: "SAO PAULO",
      codMunicipio: "3550308",
      uf: "SP",
      codPais: "1058",
      pais: "BRASIL",
    },
    emitenteJson: null,
    modalidadeFrete: "SEM_FRETE",
    transportadoraJson: null,
    valorFrete: null,
    totaisJson: {
      totalProdutos: 100,
      totalDesconto: 0,
      totalBcIcms: 0,
      totalIcms: 0,
      totalBcIpi: 0,
      totalIpi: 0,
      totalPis: 0,
      totalCofins: 0,
      totalNota: 100,
      totalTributos: 0,
    },
    notasReferenciadasJson: null,
    exportacaoJson: null,
    pagamentosJson: null,
    duplicatasJson: null,
    volumesJson: null,
    status: "DRAFT",
    createdAt: new Date(),
    updatedAt: new Date(),
    itens: [makeItem()],
    ...overrides,
  };
}
