/**
 * GERADO por `scripts/build-part-type-category-map.ts` — NÃO editar à mão.
 * Curadoria manual vai em `part-type-category-map.overrides.ts` (merge por
 * cima deste arquivo; nunca é clobberada pelo gerador).
 *
 * Cada entrada mapeia um tipo de peça canônico (label do PART_TYPES de
 * title-parse.ts, com posição dobrada opcional) para a categoria-FOLHA de cada
 * marketplace. Origem `prod-mode` = moda das categorias escolhidas manualmente
 * na base, aprovada nos gates do gerador (amostra, dominância, folha, domínio).
 *
 * Processo de atualização: rodar o gerador, revisar o DIFF deste arquivo em PR
 * próprio (a curadoria é a revisão do diff).
 */

import type { PartTypeCategoryMap } from "./part-type-category-map";

export const GENERATED_PART_TYPE_CATEGORY_MAP: PartTypeCategoryMap = {
  "abs": { ml: "MLB191710", source: "prod-mode", sampleSize: 22 },
  "airbag": { ml: "MLB47007", source: "prod-mode", sampleSize: 34 },
  "alca-de-teto": { ml: "MLB31156", source: "prod-mode", sampleSize: 75 },
  "alternador": { ml: "MLB47131", source: "prod-mode", sampleSize: 47 },
  "alto-falante": { ml: "MLB3905", source: "prod-mode", sampleSize: 69 },
  "amortecedor": { ml: "MLB22709", shopee: "102324", source: "prod-mode", sampleSize: 189 },
  "antena": { ml: "MLB45256", source: "prod-mode", sampleSize: 42 },
  "banco": { ml: "MLB46723", source: "prod-mode", sampleSize: 158 },
  "bandeja": { ml: "MLB193572", source: "prod-mode", sampleSize: 77 },
  "bandeja-traseiro-esquerdo": { ml: "MLB263651", source: "prod-mode", sampleSize: 10 },
  "barra-estabilizadora": { ml: "MLB193571", source: "prod-mode", sampleSize: 51 },
  "batente-traseiro": { ml: "MLB193623", source: "prod-mode", sampleSize: 24 },
  "bico-injetor": { ml: "MLB192566", source: "prod-mode", sampleSize: 99 },
  "bloco-motor": { ml: "MLB193390", source: "prod-mode", sampleSize: 12 },
  "bobina": { ml: "MLB22668", source: "prod-mode", sampleSize: 89 },
  "bomba-dagua": { ml: "MLB47091", source: "prod-mode", sampleSize: 49 },
  "bomba-de-combustivel": { ml: "MLB47115", source: "prod-mode", sampleSize: 112 },
  "bomba-de-direcao": { ml: "MLB193737", source: "prod-mode", sampleSize: 35 },
  "bomba-de-oleo": { ml: "MLB47106", source: "prod-mode", sampleSize: 33 },
  "braco-do-limpador": { ml: "MLB63583", source: "prod-mode", sampleSize: 67 },
  "braco-do-limpador-traseiro": { ml: "MLB432952", source: "prod-mode", sampleSize: 15 },
  "braco-oscilante": { ml: "MLB212730", source: "prod-mode", sampleSize: 11 },
  "buzina": { ml: "MLB2221", source: "prod-mode", sampleSize: 46 },
  "caixa-de-direcao": { ml: "MLB193420", source: "prod-mode", sampleSize: 47 },
  "caixa-de-fusivel": { ml: "MLB431318", source: "prod-mode", sampleSize: 35 },
  "calota": { ml: "MLB22664", source: "prod-mode", sampleSize: 25 },
  "cambio": { shopee: "102389", source: "prod-mode", sampleSize: 52 },
  "capo-direito": { ml: "MLB194777", source: "prod-mode", sampleSize: 13 },
  "capo-esquerdo": { ml: "MLB194777", source: "prod-mode", sampleSize: 12 },
  "catalisador": { ml: "MLB193146", source: "prod-mode", sampleSize: 23 },
  "chave-de-seta": { ml: "MLB63463", source: "prod-mode", sampleSize: 62 },
  "chicote": { ml: "MLB431130", source: "prod-mode", sampleSize: 266 },
  "cilindro-de-freio": { ml: "MLB47088", source: "prod-mode", sampleSize: 60 },
  "cinto-de-seguranca": { ml: "MLB194062", source: "prod-mode", sampleSize: 244 },
  "cinzeiro": { ml: "MLB22685", source: "prod-mode", sampleSize: 44 },
  "coletor": { ml: "MLB47110", source: "prod-mode", sampleSize: 122 },
  "coluna-de-direcao": { ml: "MLB270881", source: "prod-mode", sampleSize: 59 },
  "comando-de-valvulas": { shopee: "102360", source: "prod-mode", sampleSize: 32 },
  "compressor-de-ar": { ml: "MLB60608", source: "prod-mode", sampleSize: 34 },
  "condensador": { ml: "MLB190953", source: "prod-mode", sampleSize: 23 },
  "console": { ml: "MLB22704", source: "prod-mode", sampleSize: 61 },
  "corpo-de-borboleta": { ml: "MLB192357", shopee: "102339", source: "prod-mode", sampleSize: 85 },
  "coxim-inferior": { ml: "MLB194805", source: "prod-mode", sampleSize: 11 },
  "cubo-de-roda": { ml: "MLB193419", source: "prod-mode", sampleSize: 51 },
  "difusor-de-ar": { ml: "MLB47102", shopee: "102360", source: "prod-mode", sampleSize: 213 },
  "disco-de-freio": { ml: "MLB47098", source: "prod-mode", sampleSize: 31 },
  "emblema": { ml: "MLB22714", source: "prod-mode", sampleSize: 46 },
  "evaporador": { ml: "MLB190954", source: "prod-mode", sampleSize: 62 },
  "farol": { ml: "MLB7863", shopee: "102295", source: "prod-mode", sampleSize: 225 },
  "farol-de-milha": { ml: "MLB46659", source: "prod-mode", sampleSize: 55 },
  "fechadura": { ml: "MLB194431", source: "prod-mode", sampleSize: 531 },
  "fechadura-traseiro": { ml: "MLB194429", source: "prod-mode", sampleSize: 44 },
  "flauta": { ml: "MLB192359", shopee: "102344", source: "prod-mode", sampleSize: 64 },
  "forro-dianteiro-direito": { ml: "MLB431271", source: "prod-mode", sampleSize: 25 },
  "forro-dianteiro-esquerdo": { ml: "MLB431271", source: "prod-mode", sampleSize: 24 },
  "forro-direito": { ml: "MLB431271", source: "prod-mode", sampleSize: 14 },
  "forro-traseiro-esquerdo": { ml: "MLB431271", source: "prod-mode", sampleSize: 36 },
  "grade-dianteiro": { ml: "MLB63736", source: "prod-mode", sampleSize: 38 },
  "grade-direito": { ml: "MLB194704", source: "prod-mode", sampleSize: 25 },
  "lanterna": { ml: "MLB22645", shopee: "102298", source: "prod-mode", sampleSize: 577 },
  "limitador-de-porta": { ml: "MLB194800", source: "prod-mode", sampleSize: 136 },
  "luz-de-teto": { ml: "MLB22747", source: "prod-mode", sampleSize: 65 },
  "macaneta": { ml: "MLB428983", source: "prod-mode", sampleSize: 654 },
  "macaneta-dianteiro-esquerdo": { shopee: "102389", source: "prod-mode", sampleSize: 34 },
  "manga-de-eixo": { ml: "MLB277942", source: "prod-mode", sampleSize: 80 },
  "mangueira-inferior": { ml: "MLB193593", source: "prod-mode", sampleSize: 38 },
  "mangueira-superior": { ml: "MLB193593", source: "prod-mode", sampleSize: 32 },
  "maquina-de-vidro": { ml: "MLB191714", source: "prod-mode", sampleSize: 352 },
  "maquina-de-vidro-dianteiro-direito": { ml: "MLB191714", shopee: "102371", source: "prod-mode", sampleSize: 57 },
  "maquina-de-vidro-dianteiro-esquerdo": { ml: "MLB191714", shopee: "102370", source: "prod-mode", sampleSize: 42 },
  "maquina-de-vidro-traseiro": { ml: "MLB191715", source: "prod-mode", sampleSize: 12 },
  "mola": { ml: "MLB193530", source: "prod-mode", sampleSize: 137 },
  "motor-de-arranque": { ml: "MLB190976", source: "prod-mode", sampleSize: 50 },
  "painel": { shopee: "102384", source: "prod-mode", sampleSize: 27 },
  "painel-dianteiro": { ml: "MLB194739", source: "prod-mode", sampleSize: 12 },
  "parabarro": { ml: "MLB194789", source: "prod-mode", sampleSize: 84 },
  "parachoque": { shopee: "102287", source: "prod-mode", sampleSize: 44 },
  "parachoque-dianteiro": { ml: "MLB63801", shopee: "102287", source: "prod-mode", sampleSize: 72 },
  "parachoque-dianteiro-esquerdo": { ml: "MLB194773", source: "prod-mode", sampleSize: 13 },
  "parachoque-traseiro": { shopee: "102372", source: "prod-mode", sampleSize: 15 },
  "paralama": { shopee: "102532", source: "prod-mode", sampleSize: 213 },
  "pedal": { ml: "MLB270299", source: "prod-mode", sampleSize: 159 },
  "pestana": { ml: "MLB191717", source: "prod-mode", sampleSize: 100 },
  "pinca-de-freio": { ml: "MLB47099", source: "prod-mode", sampleSize: 106 },
  "pisca": { ml: "MLB22735", source: "prod-mode", sampleSize: 29 },
  "pivo": { ml: "MLB194135", source: "prod-mode", sampleSize: 30 },
  "ponta-de-eixo": { ml: "MLB264020", source: "prod-mode", sampleSize: 34 },
  "porta": { ml: "MLB101763", source: "prod-mode", sampleSize: 700 },
  "portinhola": { ml: "MLB188061", source: "prod-mode", sampleSize: 71 },
  "quebra-sol": { ml: "MLB22701", shopee: "102521", source: "prod-mode", sampleSize: 101 },
  "refletor": { ml: "MLB428943", source: "prod-mode", sampleSize: 29 },
  "reservatorio": { shopee: "102403", source: "prod-mode", sampleSize: 43 },
  "retrovisor": { ml: "MLB63846", shopee: "102392", source: "prod-mode", sampleSize: 226 },
  "semieixo": { ml: "MLB194816", source: "prod-mode", sampleSize: 77 },
  "servo-freio": { ml: "MLB191703", source: "prod-mode", sampleSize: 56 },
  "soleira": { ml: "MLB46570", source: "prod-mode", sampleSize: 121 },
  "sonda-lambda": { ml: "MLB192358", shopee: "102340", source: "prod-mode", sampleSize: 104 },
  "tambor-de-freio": { ml: "MLB63581", source: "prod-mode", sampleSize: 45 },
  "tampa-de-reservatorio": { ml: "MLB193785", shopee: "102403", source: "prod-mode", sampleSize: 63 },
  "tampa-de-tanque": { ml: "MLB188061", source: "prod-mode", sampleSize: 28 },
  "tanque-de-combustivel": { ml: "MLB194752", source: "prod-mode", sampleSize: 82 },
  "tapete": { ml: "MLB2219", source: "prod-mode", sampleSize: 78 },
  "terminal-de-direcao": { ml: "MLB194168", source: "prod-mode", sampleSize: 21 },
  "trava-estepe": { ml: "MLB271124", source: "prod-mode", sampleSize: 18 },
  "valvula-termostatica": { ml: "MLB63788", source: "prod-mode", sampleSize: 57 },
  "vareta-de-oleo": { ml: "MLB193935", source: "prod-mode", sampleSize: 25 },
  "volante-motor": { ml: "MLB430784", source: "prod-mode", sampleSize: 29 },
};
